package com.example.aichat.data

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Represents a single chat message exchanged between the user and the assistant.
 *
 * @property role The role of the message sender: system, user, assistant, or tool.
 * @property content The textual content of the message.
 * @property name Optional tool name when role is tool.
 */
@Serializable
data class Message(
    @SerialName("role") val role: MessageRole,
    @SerialName("content") val content: String,
    @SerialName("name") val name: String? = null
)

/**
 * Enumeration of possible message roles.  The `tool` role is used to represent
 * messages generated by external tools invoked by the model (e.g., web
 * search, time, location).
 */
@Serializable
enum class MessageRole {
    @SerialName("system") SYSTEM,
    @SerialName("user") USER,
    @SerialName("assistant") ASSISTANT,
    @SerialName("tool") TOOL
}